### ISSUE TITLE
[Feature] Superlike

### ISSUE THREAD

**Issue by SaturnusDJ** [tinderjs/tinder-desktop#10]
@mrmayfield 
How is superlike support going?

**Comment by mayeaux** [comment]
85% of the way there. I got the endpoint added to the forked version of tinderjs, got that version of tinderjs integrated into the desktop-app and then found where to add the code and thought of a way to do it, just haven't implemented it. Will probably get a chance next weekend, this weekend will be super busy, but it's my next no. 1 priority as far as Tinder hacking stuff goes

**Comment by SaturnusDJ** [comment]
Cool.
I added the tinderjs fork in my thing too now, manually downloaded. Then added the following to tinder++.swipe.js:

```
Mousetrap.bind('up', function () {
          var cardEl = $scope.cards[$scope.cards.length - $scope.peopleIndex - 1];
          var card = window.stack.getCard(cardEl);
          if (!!card) {
            card.throwOut(0, -100);
          }/* 
          $passOverlay = $(cardEl).children('.pass-overlay');
          $likeOverlay = $(cardEl).children('.like-overlay'); */
          superLike(1);
          ga_storage._trackEvent('Keyboard', 'up');
          window._rg.record('keyboard', 'up', { origin: 'tinderplusplus' });
        });
```

So the up key should register superlike, but I have no idea if it works. When pressing up, the current card is processed but also an error is being displayed.

**Comment by mayeaux** [comment]
Yeah, `superLike` doesn't reference anything in this case. And I'm not going to be using the cards module, I was thinking perhaps I would but I am going to use a 'swal' alert that lets you know you've just superliked and will let you know how many you have left as well.

**Comment by SaturnusDJ** [comment]
Okay, how will a user send a superlike then? With button?

**Comment by mayeaux** [comment]
I'll still bind to the keyboard up event

**Comment by SaturnusDJ** [comment]
Bummer for full OS tablet users. :stuck_out_tongue_closed_eyes: 

Apart from that, maybe we should add the pictured buttons for the actions too, like on tinder mobile.

**Comment by mayeaux** [comment]
Icons will eventually be added for superliking / unmatch, and then also likely swipe left / swipe right as well.

**Comment by SaturnusDJ** [comment]
I just merged this into the version I am using.

Two issues:
1. I superliked two chicks. This should not be possible since I don't have a premium account. Is tinder-desktop using a way to superlike more than normally possible or is the 1-per-day-limit error not implemented yet?
2. Had to run `npm install tinder` manually to get the new tinderjs downloaded, `npm install` did not do the job.

**Comment by mayeaux** [comment]
As to 1) no, it's because I haven't finished the functionality to limit the calls to superlike, any superlikes once you've run out are probably returning back as failed superlikes from the API. Will take me ~1 hour to fix and then the functionality should be complete.

2) Will check the package.json, although it _should_ be installing `tinder` module by default.

**Comment by SaturnusDJ** [comment]
Nice, good job anyways!

For issue 2 I don't know exactly how and what. Might run fine on a clean repo.

**Comment by mayeaux** [comment]
Yeah I think 2 shouldn't really be too much of an issue, it _is_ there in the package.json, we'll see if anyone else mentions it

In meantime, you should check out http://www.tinderjs.com and come join the Slack channel! :D

**Comment by SaturnusDJ** [comment]
Haha going good!
Slack says I need an invite.

**Comment by mayeaux** [comment]
If you go to that tinderjs.com link above you can email yourself an invite

**Comment by SaturnusDJ** [comment]
Ah cool, done. That wasn't yet there 5 minutes ago.

**Comment by mayeaux** [comment]
Still to do: Perhaps a countdown until you can superlike again?
