### ISSUE TITLE
Site unaccessible

### ISSUE THREAD

**Issue by rihards99** [tinderjs/tinder-desktop#139]
The trial period for [http://tinderjs.ghost.io](http://tinderjs.ghost.io) seems to have ended thus the site is effectively down. Might be a good idea to make a github page.

**Comment by mayeaux** [comment]
Hey thanks for bringing this up. I've actually deployed a ghost instance on Heroku and am going to change the DNS settings to point the domain there, will get it done this evening, thanks for the heads up. 👍

**Comment by mayeaux** [comment]
Hey sorry @rihards99 was watching the game last night (totally crazy). You can download the Windows/Mac version from the releases here in the meantime but I can get that fixed quickly.

**Comment by mayeaux** [comment]
Should be working fine now, but I am in the process of migrating to another site. Thanks for the heads up.
