### ISSUE TITLE
Stopped working on Mac 10.11.5

### ISSUE THREAD

**Issue by edglazer** [tinderjs/tinder-desktop#140]
Hey,
I was super impressed with this update of the tinder++ desktop app. Built it and got it running pretty much immediately a little over a week ago on OS X 10.11. Probably a day or 2 later, when launching the message "Loading" appears and the icon spins and spins. Previous messages appear, but no new matches since the initial launch success. Profile and discovery don't appear to be pulling the data down. One error I see in the console is:

6/7/16 9:20:23.603 AM Tinder Desktop[80046]: -[SFLListItem synthesizeMissingPropertyValues] Failed to updated bookmark for item (null) [5267A015-3DF8-4C17-BD87-09DB0CE181EB] - URL:file:///Users/xxxxxx/xxxxxxxx/xxxxxxx/etc_etc_etc_etc.pdf with error Error Domain=NSCocoaErrorDomain Code=260 "The file couldn’t be opened because it doesn’t exist."

I believe that file it is listing is the last file I double clicked on within an app. which then opened in a separate app. It was a file in Calibre which opened in Preview (the system default .pdf viewer). Not sure if that's a helpful clue, but that's what I got.

Thanks!

**Comment by mayeaux** [comment]
Huh, weird. You're deffo using the compiled version because those are Objective-C errors. How technical are you? I'd say rebuild the app and try that, or just use `gulp run` to run it with gulp as opposed to an executable binary.

**Comment by edglazer** [comment]
Looks like running 'gulp run' from the main directory throws this error:
stderr: App threw an error when running [TypeError: Cannot read property 'buildFromTemplate' of undefined]

But Electron starts and shows this error window:
Uncaught Exception:
TypeError: Cannot read property 'buildFromTemplate' of undefined
    at Object.<anonymous> (/Users/xxxx/Dev/tinder-desktop-master/desktop-app/main.js:173:16)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at loadApplicationPackage (/Users/xxxx/Dev/tinder-desktop-master/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/default_app.asar/main.js:253:23)
    at Object.<anonymous> (/Users/xxxx/Dev/tinder-desktop-master/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/default_app.asar/main.js:293:5)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)

**Comment by mayeaux** [comment]
Were you able to get this working?

**Comment by edglazer** [comment]
Nope, but after trying to both rebuild the .app and separately using `gulp run` it looks like the that TypeError only has to do with running from gulp (for some reason?). I just figured out I can view dev tools in electron. The compiled app runs, so looking at the console in dev tools, I see the spinning cursor is coming from an error in the tinder-desktop.api.js line 14 & 15. Just looking at it, I'm assuming these lines have to do with the facebook authorization? I'm willing to bet if I knew how to force it to re-authorize through fb, it would start working again. I can't find anything about how to force that to happen, though. Any suggestions?

**Comment by edglazer** [comment]
This appeared to get things running again: The tinder-desktop.api.js lines 18-29 were commented out, but were clearly meant to handle expired tokens for facebook and/or tinder. I uncommented the relevant lines, then rebuilt the desktop app and now its back in action.

Thanks again, this is great!
