### ISSUE TITLE
Google Maps API warning: NoApiKeys

### ISSUE THREAD

**Issue by EvanWillms** [tinderjs/tinder-desktop#142]
The Google Maps Places API now needs an API key in the library load:
https://developers.google.com/maps/documentation/javascript/places#loading_the_library

**Comment by mayeaux** [comment]
Two options:
- Use a different library
- Get a key that everybody can use

Any suggestions?

**Comment by mayeaux** [comment]
Actually, the module still works fine, it just complains and gives a warning. I don't really think anything needs to be done on this front, lmk what you're thinking.
