### ISSUE TITLE
can not login!

### ISSUE THREAD

**Issue by veryexoticdancer** [tinderjs/tinder-desktop#148]
First it said "You are not logged in: You are not logged in. Please log in and try again."
Then when I try to reload it several times, to login successfully, 
It said "URL Blocked: This redirect failed because the redirect URI is not whitelisted in the app’s Client OAuth Settings. Make sure Client and Web OAuth Login are on and add all your app domains as Valid OAuth Redirect URIs."

I heard there is already a version fixed that error of URIs, where can I download it?

**Comment by SaturnusDJ** [comment]
@paulxuca has found a fix. Will you open a PR Paul?

**Comment by veryexoticdancer** [comment]
@SaturnusDJ @paulxuca can you link me the download link? ... or anyone please give me a download link for the fix, thank you

**Comment by SaturnusDJ** [comment]
@veryexoticdancer 
There is no download yet. Not even an applied fix.

Just wondering, where did you get the previous working version? And was it Tinder++ or Tinder Desktop?

**Comment by veryexoticdancer** [comment]
it was plusplus, but it stopped working and now I check tinderdesktop and it has the same login error! so it is universal!

**Comment by SaturnusDJ** [comment]
Alright. We have to wait for someone who knows Javascript well.

**Comment by tadzik** [comment]
It's the same for [other 3rdparty tinder clients](https://openrepos.net/content/minitreintje/sailfinder), seems like something screwed on facebook/tinder side that needs changes everywhere. Fwiw, the official tinder app stopped working for me too :/

**Comment by mayeaux** [comment]
Yup, and @paulxuca has a fix that he's using in one his own modules, but hasn't slapped it into tinder-desktop. It'd probably take a few hours, but I must say I don't use tinder-desktop anymore so I don't have a big incentive to do it! Probably if you offered myself or Paul some PayPal dollars we would be more motivated to fix it for everybody but I have to say it's kinda low on my priority list atm 😕 hopefully I'll have a chance this weekend we'll see

**Comment by SaturnusDJ** [comment]
@stuwil @run1t 
You have some time maybe?

**Comment by baskervald** [comment]
I was planning on writing a sloppy fix for myself, honestly, so when I'm done I'll share that. I have no real plans of cleaning it up given for me it's just a quickfix, though.

**Comment by mfkp** [comment]
Here's my fix for this one, should be pretty straightforward to port it over to `tinder-desktop.login.js`

https://github.com/mfkp/tinderplusplus/commit/0a7cf59e4969c89ceb7836d28255b95e34ce6035

**Comment by SaturnusDJ** [comment]
Hey mannn, welcome back!

Replacing as you did for T++ doesn't seem to work for TD. :(

**Comment by mfkp** [comment]
Thanks, got a ton of emails about it, figured it needed a fix.

What seems to be the problem? It looks like you'll also need to parse out the `expires_in` value, since you're using that as well.

**Comment by SaturnusDJ** [comment]
So still a lot of users, nice.

I have no idea how to fix it. I'm the CSS guy. No JS.

**Comment by veryexoticdancer** [comment]
@mfkp thank you.

**Comment by SaturnusDJ** [comment]
@mfkp 
Do you know the TD fix?
I've played around with removing the line and related ones but didn't get into the app.

**Comment by mayeaux** [comment]
Okay thanks for the update @mfkp . Will try and get this up and running within the next couple days.

**Comment by mayeaux** [comment]
Yeah @mfkp I see the flow you're using, but my flow never redirects to `https://m.facebook.com/v2.6/dialog/oauth/confirm` and thus (as far as I can see) I never am able to access the token. If you're around would help to go back and forth a couple times til I get it figured.

**Comment by mfkp** [comment]
It should redirect to that after they authorize the tinder permission, or
hit OK to confirm they have already authorized it. Does that not happen for
you?

**Comment by mayeaux** [comment]
No, it doesn't do that for me. It doesn't do it on Tinder++ either, and thus doesn't log me into Tinder++ either

**Comment by mfkp** [comment]
Hm, that's strange, it's been working fine for me. Could it be an issue
with the Facebook account you're using? Have you tested with another
account?

**Comment by mayeaux** [comment]
Just tested with another acct. Same thing. Can't get developer tools to open either with NW.js so I can't really poke around and test things. We'll see, I do get this error coming through when I use NW.js

```
chrome-extension://eabpbhcbkeckibejgbdcdmegannhncad/js/error_handler.js:7
if (process._events.uncaughtException.length > 0) {
                                     ^

TypeError: Cannot read property 'length' of undefined
    at chrome-extension://eabpbhcbkeckibejgbdcdmegannhncad/js/error_handler.js:7:38
```

maybe it's related, not sure.

**Comment by mayeaux** [comment]
Hm, I just tried it with NW 0.11.6 and it worked. So probably the version of Chromium being different is causing it. 🤔

**Comment by mfkp** [comment]
Yeah, I do have the version locked at 0.11.6 because they made some
breaking changes after that. Been a long time, so I don’t remember exactly
what it was.

On August 15, 2016 at 10:45:52 AM, Anthony Mayfield (
notifications@github.com) wrote:

Hm, I just tried it with NW 0.11.6 and it worked. So probably the version
of Chromium being different is causing it. 🤔

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
https://github.com/tinderjs/tinder-desktop/issues/148#issuecomment-239873077,
or mute the thread

**Comment by mayeaux** [comment]
Yeah it's weird that the later versions of Chrome/Chromium don't redirect properly (since tinder-desktop uses electron now). I may investigate it a bit, or @litdevelopers has an implementation here: 

https://github.com/litdevelopers/tinder/blob/master/server/api/facebookAuth.js
https://github.com/litdevelopers/tinder/blob/master/server/api/api.js

That's a little bit overly complex (could probably be cleaned up though), which I'll probably end up implementing. I haven't used tinder-desktop in months now lol I must admit, but I'll have this fixed by the end of the week at the latest.

**Comment by mayeaux** [comment]
Spent a couple hours on it today with no luck. 

If you guys can solve: http://stackoverflow.com/questions/38960592/facebook-oauth-redirect-not-working-properly-with-later-versions-of-electron

I can get it working np. Without that though it looks like it either won't work or the implementation to make it work will be pretty horrendous.

**Comment by SaturnusDJ** [comment]
Alright, thanks @stuwil ❤️ 

I've updated my compiled version for Win at http://members.home.nl/saturnusdj/Tinder_Desktop
Tested to be working at main and win7 VM.
@veryexoticdancer 
Maybe interesting for you to try Tinder Desktop

OSX hopefully later today.

**Comment by SaturnusDJ** [comment]
OSX up too.

**Comment by SaturnusDJ** [comment]
@stuwil
I think there is still some kind of bug. Sometimes chats don't get updated and profiles don't load. Clearing cache and signing in, and it works for 'a while' again.
As if Auth fails, but this time the GUI doesn't tell the user, and neither signing him/her out automatically, as before.

**Comment by veryexoticdancer** [comment]
@SaturnusDJ I will try when it is stable, hearing that it doesnt update chat and profiles sometimes doesn't load made me a bit scared to try it.

**Comment by SaturnusDJ** [comment]
Definitely some stuff is broken. Like logout doesn't work (-> manually remove cache folder). And the non-updating TD might be because it only allows one active computer (->resign in).

That said, at least for me, even with these downsides, I got too used to the functionality, bigger profile pictures etc, so I'll continue using. Dropping small css update later today.

**Comment by Marooned-MB** [comment]
This is still not working. Probably settings for client_id=464891386855067 are wrong in Facebook?
The error is the same as in 1st comment.

Change from https://github.com/tinderjs/tinder-desktop/issues/148#issuecomment-239726776 did not worked either. Got a popup that I've already authorised Tinder app, but there is no redirection nor token available to grab from page url/body.

**Comment by SaturnusDJ** [comment]
Are you using my compiles?

http://members.home.nl/saturnusdj/Tinder_Desktop
Should work, except for the bug described on that page.

**Comment by Marooned-MB** [comment]
Nope, I did not. I can see it's .exe and I'm quite restricted here on running executables. It's nothing I need - just wanted to give it a try, got error and report it. No big deal without that app. Thanks.
[edited]
Ok, found your repo and run from sources. Got some error after logging in but after rejecting it the app seems to be working fine. Thanks again!

**Comment by mayeaux** [comment]
Perfect, glad to hear! Enjoy!
