### ISSUE TITLE
Not Logged In: You are not logged in. Please login and try again.

### ISSUE THREAD

**Issue by galaxy-nomad** [tinderjs/tinder-desktop#153]
On Yosemite 10.10.5 with VPN running. When I try to log in to FaceBook I get a white pop-up window that says "Not Logged In: You are not logged in. Please login and try again." There is nothing else in this window, no FaceBook log-in button etc...

**Comment by mayeaux** [comment]
Did you download an executable from Releases? Or how are you running the app?

**Comment by galaxy-nomad** [comment]
First I downoad the app at http://tinderplusplus.com/ and that would not login to FaceBook. It opened a blank white Safari like browser window with no information in it. Next I downloaded the app at https://tinderjsblog.herokuapp.com/download/ and that gave me the issue I reported here. Now I'm downloading the app at http://members.home.nl/saturnusdj/Tinder_Desktop/ and that one appears to successfuly log in but it never actually shows me Tinder. It stays on the Tinder "TD" Logo page with the blue login button at the bottom. If I try to login again it says that I have already authorized Tinder but it never actually goes past the splash startup screen.

**Comment by galaxy-nomad** [comment]
As a fourth option I just tried the Mac version in your releases section and it gave me the same error as I posted in the thread title.

**Comment by toinbis** [comment]
Same error here. Both by downloading OSX application as well as launching it from the terminal with "gulp run".

**Comment by toinbis** [comment]
Same error on Widows

**Comment by galaxy-nomad** [comment]
Version 0.1.0 Beta works perfectly. I just can't use it with VPN enabled. The official Tinder app for iOS does not work wth VPN either so it must be an issue with the Tinder API.

**Comment by toinbis** [comment]
Just to add that in my case no VPN was being used at all. I simply can not get the app working. Any way to see the logs and find the cause of an error?

**Comment by galaxy-nomad** [comment]
@toinbis Are you on a Mac? If so make sure to use the 0.1.0 Beta. I had positive results with that build as long as VPN was disabled:-)

**Comment by edglazer** [comment]
I have to manually delete my tinder token each time to get it to work. This is on a mac (10.11.6, version 0.10.0)

First, by selecting View > Toggle Developer Tools. Then selecting (from Resources) Local Storage > file:// > TinderToken and clicking on the 'delete' X towards the bottom window. 

Then I have to quit and restart the program and give facebook permission again and it works fine.

**Comment by SaturnusDJ** [comment]
@edglazer 
Same here otherwise the app data won't update.
You can make this process more simple by creating a batch file that deleted all TD data. Then start TD.
The folder is in %APPDATA%/Roaming I believe, for Win.
For Mac in your user folder Library/Application Support/Tinder Desktop.

**Comment by galaxy-nomad** [comment]
Just an update I may have been mistaken above because now the latest beta 0.1.0 doesn't work. The one that is working currently is at http://members.home.nl/saturnusdj/Tinder_Desktop/

**Comment by mayeaux** [comment]
I'll update the executables this weekend.
