### ISSUE TITLE
[Discussion] Future and strategy of tinder-desktop

### ISSUE THREAD

**Issue by SaturnusDJ** [tinderjs/tinder-desktop#3]
Hey @mrmayfield 

How is it going now? I hope you can provide the latest information on the project.
I see my GUI commits aren't pulled yet.

Best would be to have some kind of strategy going.
Who is on what part of development. Who oversees it all. What are our objectives. Etc.

Talking about this in private is of course an option too.

Cheers!

**Comment by mayeaux** [comment]
Yup, I agree with this 100%, and let's use this as the place to discuss overall vision. I'm going to open another Issue to discuss GUI changes and I will bring up the changes you've made there :)

**Comment by mayeaux** [comment]
Here are my personal priorities, and during the weekdays I have a job where I'm mostly working at throughout most of the day so I don't have so much time to work on this project, it will mostly be on the weekend where I can code for this project. 
1. Superlike Support <- This will require adding the endpoint for it into the `tinderjs` module, and then wiring it into the app
2. Automatic liking system 
3. Unmatch Support <- This will also require adding the endpoint into `tinderjs`

Then, almost as much for fun I am going to sniff out a couple more endpoints. Perhaps the Passport (change match location) endpoint and profile photo add / remove endpoints. Will try and get those documented for the community.

Then, 
1. Receive notifications for sent messages (including fixing a bug with lastActivity)
2. Show time in messages (mostly frontend) 
3. Kilometres support
4. Liked messages (needs to be added to API)

That's what I'm thinking. Wouldn't mind throwing in changing the app to use all of the desktop screen as well as the big frontend change ;)

**Comment by SaturnusDJ** [comment]
I like your list! Automatic liking I won't use but the others are great and really handy.
If you have a push in the right direction for 'show time in messages' I can already look at it.

**Comment by stuwil** [comment]
Closing as we have the [Development Priorities](https://github.com/tinderjs/tinder-desktop/wiki/Development-Priorities) and release milestones now.
