### ISSUE TITLE
NW 0.13.x compatibility 

### ISSUE THREAD

**Issue by run1t** [tinderjs/tinder-desktop#39]
For the moment it's impossible to login with the 0.13.x version of nw, you should have those errors : 
<img width="581" alt="capture d ecran 2016-04-10 a 19 58 37" src="https://cloud.githubusercontent.com/assets/6145328/14411620/ca17e39a-ff5e-11e5-872d-11614dcb5930.png">

```
Uncaught TypeError: Cannot read property 'length' of undefined
util.js:220 Google Maps API warning: NoApiKeys https://developers.google.com/maps/documentation/javascript/error-messages#no-api-keys
angular.min.js:101 TypeError: Cannot read property 'on' of undefined
    at k.LoginController.$scope.startLogin (tinder++.login.js:22)
    at angular.min.js:197
    at f (angular.min.js:226)
    at k.$eval (angular.min.js:124)
    at k.$apply (angular.min.js:125)
    at HTMLAnchorElement.<anonymous> (angular.min.js:226)
    at HTMLAnchorElement.c (angular.min.js:32)
```

**Comment by mayeaux** [comment]
Yeah I am pretty familiar with this section of the code. It looks like the automatic URL checker that finds the token is not working properly. Should be a relatively simple fix
