### ISSUE TITLE
[Bug] Something with emoji / cookie killer --> need to login to fb again

### ISSUE THREAD

**Issue by SaturnusDJ** [tinderjs/tinder-desktop#6]
Error log:

[bug_emoji.txt](https://github.com/tinderjs/tinder-desktop/files/180048/bug_emoji.txt)

**Comment by mayeaux** [comment]
How was this bug produced, what steps can I take to try and reproduce it?

**Comment by SaturnusDJ** [comment]
No idea, it just happens sometimes.

**Comment by mayeaux** [comment]
Can you post the error log here in this issue rather than a separate text file?

**Comment by mayeaux** [comment]
Frankly, I think I'm going to rework the emoji setup, it doesn't work very well and the emojis are hella ugly.

**Comment by mayeaux** [comment]
Can you post the error here?
