### ISSUE TITLE
Show total number of matches

### ISSUE THREAD

**Issue by mayeaux** [tinderjs/tinder-desktop#7]
If we run

`response = await client.getHistoryAsync ()`

we can find the number of matches by 

`response.matches.length`

Would be nice to have this data displayed somewhere

**Comment by SaturnusDJ** [comment]
![matchcount](https://cloud.githubusercontent.com/assets/14320018/14066163/166bf65e-f443-11e5-93d2-df45b7fad291.png)

How to have it available in HTML?
Put the first line of code somewhere in tinder++.api.js?
I've no idea.

**Comment by mayeaux** [comment]
Yup no problem, it's somewhat low priority for me at the moment, hoping to have Superlike support up within the next couple hours. I've also made some pretty hilarious bots as well haha.

**Comment by SaturnusDJ** [comment]
Since this is a small one, can you explain how to implement it?

**Comment by mayeaux** [comment]
Somewhere in the code, we are calling client.getHistory and receiving `data` back. From that data, we can look at `data.matches.messages.length` to get the total number of active matches, then will have to pass that to the angular view somehow.

**Comment by SaturnusDJ** [comment]
Yeah 
`client.getHistory(function(err, res) {`
is in tinder++.api.js
(In my 'unstable' branch, that should be stable and bugless now, I removed function data, because it's called nowhere.)

I tried to understand, but from here I am clueless already.

**Comment by mayeaux** [comment]
Don't worry, I will add it eventually, although it is pretty low priority.

What do you mean when you say you removed function data?

**Comment by SaturnusDJ** [comment]
True I know, but I want to understand all the code. Very hard.

It's shown here: https://github.com/SaturnusDJ/tinder-desktop/commit/48f2c401f3076a221cc34d07d2dbbd85195eb2c3

App still working so I guess it's ok.
