### ISSUE TITLE
Clean up design of the messages page

### ISSUE THREAD

**Issue by hanford** [tinderjs/tinder-desktop#74]
Hey guys, I can see myself spending a lot of time this application :p I want to make sure it looks neat too.

I did some minor UI tweaks to the messages page, thoughts?

<img width="1217" alt="screen shot 2016-04-17 at 1 41 22 pm" src="https://cloud.githubusercontent.com/assets/2148168/14589913/86fe2d82-04a2-11e6-91d6-66e6ad8deec2.png">
- Remove blacked unmatch heart, in favor of the right nav Unmatch button
- Add fixed Messages header, to conversation list displaying total amount of conversations
- Shrink Nav icons / text to fit inside newly defined center navbar

**Comment by SaturnusDJ** [comment]
Match count is nice!
Msg bubbles look a bit full.

Concerning the UI, I am almost done with a reworked version (few days to go). Best would be to hold back for a while, otherwise much merge conflicts.

**Comment by hanford** [comment]
@SaturnusDJ Should I open a new PR with just the total messages / messages header to address https://github.com/tinderjs/tinder-desktop/issues/7

**Comment by SaturnusDJ** [comment]
Yeah would be nice if that got pulled, then I can see how it looks in the improved UI.
