### ISSUE TITLE
Installation / build scripts

### ISSUE THREAD

**Issue by mayeaux** [tinderjs/tinder-desktop#86]
Can we proxy `npm install` to a build script that will run our 2 `npm install` commands and also `bower install` ? I've done this on other projects with a lot of success, maybe we can map `npm build` to gulp as well

**Comment by hanford** [comment]
Potentially relevant: https://github.com/tinderjs/tinder-desktop/issues/72

**Comment by stuwil** [comment]
npm build is an internal command that can't be overwritten. It would have to be invoked as npm run-script build, which isn't much better than gulp build:all.

Can definitely hook into npm install though.
